#include "resampler.h"

#define SOXR_DEFAULT_QUALITY SOXR_MQ
#define SOXR_DEFAULT_PHASE SOXR_LINEAR_PHASE
#define SOXR_DEFAULT_STEEP_FILTER FALSE
#define DEFAULT_INPUT_BUFFER_LENGTH 100
#define DEFAULT_PLAYBACK_BUFFER_LENGTH 300
#define DEFAULT_BACKGROUND FALSE
#define DEFAULT_KEEP_ALIVE FALSE
#define DEFAULT_NO_DITHER FALSE

#define MIN_BUFFER_LEGNTH 10
#define MAX_BUFFER_LENGTH 10000

BOOL resampler_settings_create(BASS_SOX_RESAMPLER* resampler);

BOOL resampler_settings_free(BASS_SOX_RESAMPLER* resampler);